# Generated by Django 4.1.3 on 2022-12-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('income', 'รายรับ'), ('expense', 'รายจ่าย')], max_length=100)),
            ],
        ),
    ]
